CREATE TABLE QuanlyNhanSu (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    age INT(11) NOT NULL,
    address VARCHAR(100) NOT NULL,
    workday DATE NOT NULL,
    sex VARCHAR(10) NOT NULL,
    part VARCHAR(50) NOT NULL,
    position VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);